class ValidatedError(Exception):
    """Класс ошибки валидации"""
    pass


class HasOwnerError(Exception):
    """Класс ошибки присвоения, в уже занятую ячейку"""
    pass

